pygments: true
permalink: /posts/:title

name: Ryan Frantz
url: http://www.ryanfrantz.com
description: Ryan Frantz
twitter: Ryan_Frantz
github: RyanFrantz
gravatar_url: http://www.gravatar.com/avatar/ac597d5209b6e5b648f49a1e73440ef3.png
